# Generated by python -m roboz.endpoints inventory; DO NOT EDIT.
"""Project model snapshot. Edit its JSON source and re-run inventory generate."""

from typing import TYPE_CHECKING as _TYPE_CHECKING
from roboz.endpoints.catalog import Catalog as _Catalog
from roboz.endpoints.adapters.openai_compatible import OpenAICompatibleAdapter as _OpenAICompatibleAdapter
from roboz.endpoints.specs import ChatModelSpec as _ChatModelSpec
from roboz.endpoints.specs import TranscriptionModelSpec as _TranscriptionModelSpec

_ROBOZ_ENDPOINTS_INVENTORY = {'schema_version': 1,
 'providers': {'groq': {'base_url': 'https://api.groq.com/openai/v1',
                        'api_key_env': 'GROQ_API_KEY_SECRET',
                        'timeout_s': 60.0,
                        'stream': True,
                        'models': {'whisper_large_v3_turbo': {'model_id': 'whisper-large-v3-turbo',
                                                              'endpoint_type': 'transcription'},
                                   'new_chat': {'model_id': 'new-chat',
                                                'max_context_tokens': 256,
                                                'endpoint_type': 'llm'}}},
               'custom': {'base_url': 'https://models.example.com/v1',
                          'api_key_env': 'CUSTOM_API_KEY_SECRET',
                          'timeout_s': 12.0,
                          'stream': False,
                          'models': {'chat': {'model_id': 'custom/chat',
                                              'max_context_tokens': 1024,
                                              'endpoint_type': 'llm'},
                                     'audio': {'model_id': 'custom/audio',
                                               'endpoint_type': 'transcription'}}}}}

if _TYPE_CHECKING:
    from roboz.llm import LLMEndpoint as _LLMEndpoint
    from roboz.llm import TranscriptionEndpoint as _TranscriptionEndpoint
    from roboz.endpoints.specs import ModelSpec as _ModelSpec

    class _groq_Catalog(_Catalog[_ModelSpec]):
        whisper_large_v3_turbo: _TranscriptionEndpoint
        new_chat: _LLMEndpoint

    groq: _groq_Catalog

    class _custom_Catalog(_Catalog[_ModelSpec]):
        chat: _LLMEndpoint
        audio: _TranscriptionEndpoint

    custom: _custom_Catalog
else:
    _namespace = globals()
    _spec_types = {_ChatModelSpec.endpoint_type: _ChatModelSpec, _TranscriptionModelSpec.endpoint_type: _TranscriptionModelSpec}
    for _name, _provider in _ROBOZ_ENDPOINTS_INVENTORY['providers'].items():
        _models = {}
        for _attribute, _record in _provider['models'].items():
            _values = _record.copy()
            _spec = _spec_types[_values.pop('endpoint_type')]
            _models[_attribute] = _spec(**_values)
        _settings = {_field: _provider[_field] for _field in ('base_url', 'api_key_env', 'timeout_s')}
        _namespace[_name] = _Catalog(
            adapter=_OpenAICompatibleAdapter(api_name=_name, **_settings),
            models=_models, stream=_provider['stream'],
        )

__all__ = ['groq', 'custom']
