"""Shared helpers for `run_file_command` and related CLI tools."""

from .cmd_spec import ArgPattern, CmdSpec
from .constants import (
    ERR_ARGS_NOT_ALLOWED,
    ERR_COMMAND_NOT_ALLOWED,
    ERR_COMMAND_NOT_FOUND,
    ERR_EXIT_NONZERO,
    ERR_EXIT_NONZERO_NO_OUTPUT,
    ERR_FORBIDDEN_PATTERN,
    ERR_HINT_USE_HELP,
    ERR_NO_PATHS,
    ERR_TIMEOUT,
    GLOB_CHARS,
    PIPE_OUTPUT_TO_NEXT_COMMAND,
    PIPE_STDIN_FROM_PREVIOUS_COMMAND,
    SUBPROCESS_TIMEOUT_SECONDS,
    SUCCESS_NO_OUTPUT,
    WILDCARD_PATTERN,
)
from .formatting import (
    cli_help_message,
    format_cli_commands_help,
    format_cli_constraints,
    format_cli_full_help,
)
from .path_extractors import (
    cat_path_args,
    diff_path_args,
    find_path_args,
    gio_trash_path_args,
    grep_path_args,
    head_path_args,
    ls_path_args,
    mkdir_path_args,
    rg_path_args,
    resolve_path_indices,
    tail_path_args,
    tee_path_args,
    touch_path_args,
    wc_path_args,
)

__all__ = [
    "ArgPattern",
    "CmdSpec",
    "ERR_ARGS_NOT_ALLOWED",
    "ERR_COMMAND_NOT_ALLOWED",
    "ERR_COMMAND_NOT_FOUND",
    "ERR_EXIT_NONZERO",
    "ERR_EXIT_NONZERO_NO_OUTPUT",
    "ERR_FORBIDDEN_PATTERN",
    "ERR_HINT_USE_HELP",
    "ERR_NO_PATHS",
    "ERR_TIMEOUT",
    "GLOB_CHARS",
    "PIPE_OUTPUT_TO_NEXT_COMMAND",
    "PIPE_STDIN_FROM_PREVIOUS_COMMAND",
    "SUBPROCESS_TIMEOUT_SECONDS",
    "SUCCESS_NO_OUTPUT",
    "WILDCARD_PATTERN",
    "cli_help_message",
    "format_cli_commands_help",
    "format_cli_constraints",
    "format_cli_full_help",
    "cat_path_args",
    "diff_path_args",
    "find_path_args",
    "gio_trash_path_args",
    "grep_path_args",
    "head_path_args",
    "ls_path_args",
    "mkdir_path_args",
    "rg_path_args",
    "resolve_path_indices",
    "tail_path_args",
    "tee_path_args",
    "touch_path_args",
    "wc_path_args",
]
