"""Versioned, credential-free serialization of editable inventory snapshots."""

import ast
from dataclasses import MISSING, asdict, dataclass, fields
from inspect import signature
import json
from keyword import iskeyword
import math
from pathlib import Path
from typing import Any, get_args
import unicodedata
from urllib.parse import urlsplit

from roboz.endpoints.adapters.openai_compatible import OpenAICompatibleAdapter
from roboz.endpoints.catalog import Catalog
from roboz.endpoints.specs import ModelSpec


MARKER = "# Generated by python -m roboz.endpoints inventory; DO NOT EDIT."
DATA_NAME = "_ROBOZ_ENDPOINTS_INVENTORY"
SCHEMA_VERSION = 1
MODEL_KIND_FIELD = "endpoint_type"
MODEL_SPEC_TYPES: tuple[type[ModelSpec], ...] = get_args(ModelSpec.__value__)
_MODEL_TYPES_BY_KIND = {spec.endpoint_type: spec for spec in MODEL_SPEC_TYPES}


@dataclass(frozen=True, kw_only=True)
class Provider:
    """Version-1 provider fields, with explicit defaults and no credential values.

    These persisted defaults intentionally stay independent of future changes
    to runtime constructor defaults. Model fields come from the model specs.
    """

    base_url: str
    api_key_env: str
    timeout_s: float = 60.0
    stream: bool = True
    models: dict[str, ModelSpec]

    def adapter_settings(self) -> dict[str, Any]:
        """Select declared inventory fields accepted by the service adapter."""
        return {name: getattr(self, name) for name in ADAPTER_FIELDS}


ADAPTER_FIELDS = tuple(
    field.name
    for field in fields(Provider)
    if field.name in signature(OpenAICompatibleAdapter).parameters
)


type Inventory = dict[str, Provider]


def identifier(value: str, field: str) -> str:
    """Require a public, normalized Python identifier safe for generated bindings."""
    if (
        not value.isidentifier()
        or value.startswith("_")
        or iskeyword(value)
        or unicodedata.normalize("NFKC", value) != value
    ):
        raise ValueError(f"{field}: use a public Python identifier, not {value!r}")
    return value


def _object(value: object, field: str) -> dict[str, Any]:
    if not isinstance(value, dict) or not all(isinstance(k, str) for k in value):
        raise ValueError(f"{field}: expected an object with named entries")
    return value


def _fields(
    value: dict[str, Any], required: set[str], optional: set[str], field: str
) -> None:
    missing = required - value.keys()
    unknown = value.keys() - required - optional
    if missing:
        raise ValueError(f"{field}: missing fields {', '.join(sorted(missing))}")
    if unknown:
        raise ValueError(f"{field}: unknown fields {', '.join(sorted(unknown))}")


def _string(value: object, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{field}: expected a nonblank string")
    return value


def _scalar(value: object, annotation: object, field: str) -> Any:
    """Validate the scalar types used by inventory records without JSON coercion."""
    if annotation is str:
        return _string(value, field)
    if annotation is bool:
        if type(value) is not bool:
            raise ValueError(f"{field}: expected a boolean")
        return value
    if annotation is int:
        if type(value) is not int or value <= 0:
            raise ValueError(f"{field}: expected a positive integer")
        return value
    if annotation is float:
        if type(value) is not int and type(value) is not float:
            raise ValueError(f"{field}: expected a finite positive number")
        try:
            valid = math.isfinite(value) and value > 0
        except OverflowError:
            valid = False
        if not valid:
            raise ValueError(f"{field}: expected a finite positive number")
        return float(value)
    raise TypeError(f"{field}: unsupported inventory scalar type {annotation}")


def _record_values(
    record: dict[str, Any],
    schema: type[Provider] | type[ModelSpec],
    field: str,
    *,
    nested: frozenset[str] = frozenset(),
    metadata: frozenset[str] = frozenset(),
) -> dict[str, Any]:
    """Decode dataclass scalar fields; callers handle nested records and kind tags."""
    declared = fields(schema)
    required = {item.name for item in declared if item.default is MISSING}
    optional = {item.name for item in declared if item.default is not MISSING}
    _fields(record, required | set(metadata), optional, field)
    return {
        item.name: _scalar(
            record.get(item.name, item.default), item.type, f"{field}.{item.name}"
        )
        for item in declared
        if item.name not in nested
    }


def _parse_model(value: object, field: str) -> ModelSpec:
    record = _object(value, field)
    kind = record.get(MODEL_KIND_FIELD)
    if not isinstance(kind, str) or kind not in _MODEL_TYPES_BY_KIND:
        choices = " or ".join(repr(kind) for kind in _MODEL_TYPES_BY_KIND)
        raise ValueError(f"{field}.{MODEL_KIND_FIELD}: expected {choices}")
    spec = _MODEL_TYPES_BY_KIND[kind]
    values = _record_values(record, spec, field, metadata=frozenset({MODEL_KIND_FIELD}))
    return spec(**values)


def _parse_models(value: object, field: str) -> dict[str, ModelSpec]:
    return {
        identifier(name, f"{field}.{name}"): _parse_model(record, f"{field}.{name}")
        for name, record in _object(value, field).items()
    }


def _parse_provider(name: str, value: object) -> Provider:
    field = f"providers.{name}"
    identifier(name, field)
    record = _object(value, field)
    settings = _record_values(record, Provider, field, nested=frozenset({"models"}))
    provider = Provider(
        **settings, models=_parse_models(record["models"], f"{field}.models")
    )
    adapter = OpenAICompatibleAdapter(api_name=name, **provider.adapter_settings())
    try:
        adapter._validate_service_settings()
        # Reject invalid/out-of-range ports, even for empty providers.
        urlsplit(provider.base_url).port
    except ValueError as error:
        raise ValueError(f"{field}.base_url: {error}") from error
    try:
        Catalog(adapter=adapter, models=provider.models, stream=provider.stream)
    except ValueError as error:
        raise ValueError(f"{field}.models: {error}") from error
    return provider


def parse_document(document: object) -> Inventory:
    """Validate the document envelope, then decode each provider independently."""
    root = _object(document, "inventory")
    _fields(root, {"schema_version", "providers"}, set(), "inventory")
    if (
        type(root["schema_version"]) is not int
        or root["schema_version"] != SCHEMA_VERSION
    ):
        raise ValueError(f"schema_version: expected supported version {SCHEMA_VERSION}")
    return {
        name: _parse_provider(name, value)
        for name, value in _object(root["providers"], "providers").items()
    }


def document_from_inventory(inventory: Inventory) -> dict[str, Any]:
    """Serialize declared dataclass fields and the specs' class-level kind tags."""
    providers = {}
    for name, provider in inventory.items():
        record = asdict(provider)
        record["models"] = {
            attribute: {**asdict(model), MODEL_KIND_FIELD: model.endpoint_type}
            for attribute, model in provider.models.items()
        }
        providers[name] = record
    return {"schema_version": SCHEMA_VERSION, "providers": providers}


def bundled_inventory() -> Inventory:
    """Describe bundled settings without selecting model attributes or exporting keys."""
    from roboz.endpoints.inventory import CATALOGS

    inventory = {
        name: Provider(
            base_url=collection._adapter._base_url,
            api_key_env=collection._adapter._api_key_env,
            timeout_s=collection._adapter._timeout_s,
            stream=collection._stream,
            models=dict(collection.models_by_attribute),
        )
        for name, collection in CATALOGS.items()
    }
    return parse_document(document_from_inventory(inventory))


class _Pairs(list):
    """Retain object pairs until duplicate keys can be diagnosed with their path."""


def _unpack(value: Any, field: str = "inventory") -> Any:
    if isinstance(value, _Pairs):
        result = {}
        for key, child in value:
            if key in result:
                raise ValueError(f"{field}.{key}: duplicate JSON key")
            result[key] = _unpack(child, f"{field}.{key}")
        return result
    if isinstance(value, list):
        return [_unpack(child, field) for child in value]
    return value


def read_json(path: Path) -> Inventory:
    """Read JSON and report validation failures with their source path."""
    try:
        return parse_document(
            _unpack(
                json.loads(path.read_text(encoding="utf-8"), object_pairs_hook=_Pairs)
            )
        )
    except (ValueError, RecursionError) as error:
        raise ValueError(f"{path}: {error}") from error


def render_json(inventory: Inventory) -> str:
    """Serialize an editable snapshot with explicit defaults and a final newline."""
    return (
        json.dumps(document_from_inventory(inventory), indent=2, allow_nan=False) + "\n"
    )


def read_module(path: Path) -> Inventory:
    """Extract marked literal data without executing generated or user Python code."""
    try:
        source = path.read_text(encoding="utf-8")
        if not source.startswith(MARKER + "\n"):
            raise ValueError(
                "expected a module generated by python -m roboz.endpoints inventory import"
            )
        tree = ast.parse(source)
        values = [
            node.value
            for node in tree.body
            if isinstance(node, ast.Assign)
            and any(
                isinstance(target, ast.Name) and target.id == DATA_NAME
                for target in node.targets
            )
        ]
        if len(values) != 1:
            raise ValueError("expected exactly one embedded inventory literal")
        return parse_document(ast.literal_eval(values[0]))
    except (TypeError, ValueError, SyntaxError, RecursionError) as error:
        raise ValueError(f"{path}: {error}") from error
