"""Typing surface for :mod:`roboz.standard.providers.openrouter`.

AUTO-GENERATED by ``scripts/generate_provider_stubs.py``. Do not edit.
"""

from enum import StrEnum

from openai import OpenAI
from roboz.llm import LLMEndpoint
from roboz.tooling import LazyExternalDependency

from roboz.llm.providers.catalog import ProviderCatalog
from roboz.llm.providers.model_types import ChatModelSpec

OPENROUTER_BASE_URL: str
OPENROUTER_MODELS: tuple[ChatModelSpec, ...]

class OpenRouterApiKey(StrEnum):
    API_KEY: OpenRouterApiKey

def openrouter_client(api_key: str) -> OpenAI: ...
def openrouter_model_name(model: ChatModelSpec) -> str: ...
def openrouter_endpoint(model: ChatModelSpec, model_name: str) -> LLMEndpoint: ...

class OpenRouterCatalog(ProviderCatalog):
    def __init__(self) -> None: ...
    z_ai__glm_5_3_flash: LazyExternalDependency[LLMEndpoint]

openrouter: OpenRouterCatalog

__all__: list[str]
