"""Provide short Simpsons quotes collected from Reddit discussions.

Sources are fan recollections; punctuation and capitalization are normalized.
"""

from typing import Final

QUOTES: Final[list[str]] = [
    "Me fail English? That’s unpossible.",
    "Little bit of column A, little bit of column B.",
    "At first I was just full of vinegar!",
    "Haha, nobody ever says Italy.",
    "Some people say evasion, I say avoision.",
    "Trying is the first step toward failure.",
    "Kids, you tried your best and you failed miserably. The lesson is, never try.",
    'Maybe for once, someone will call me "sir" without adding, "You\'re making a scene."',
    "Please refrain from tasting the knob!",
    "Money can be exchanged for goods and services.",
    "Whoa, whoa, slow down, egghead!",
    "It's my first day.",
    "It takes two to lie. One to lie and one to listen.",
    "It's a boy, and what a boy!",
    "I told you, my baby beat me up!",
    "We've tried nothing and we're all out of ideas.",
    "You don't get rich by writing a lot of checks.",
    "Good evening, sir. Would you please leave without a fuss right now?",
    "Save me Jebus!",
    "Eat my shorts!",
    "To alcohol, the cause of, and solution to, all of life's problems.",
    "Purple's a fruit.",
    "That's a paddlin'.",
    "Bake 'em away, toys!",
    "Meh. M-E-H. Meh.",
    "My boy's a box! Damn you! A box!",
    "Care to join me in a belt of scotch?",
    "I'm all hopped up on goofballs.",
    "D'oh!",
    "Everything's coming up Milhouse!",
    "Go banana!",
    "Yoink!",
    "Ha-ha!",
    "Smell ya later!",
    "Now with vitamin R!",
    "Me fail English? Unpossible!",
    "The goggles! They do nothing!",
    "If you don't like your job, you don't go on strike; you go in every day and do it really half assed",
    "I don't want to look like a weirdo, I'll just wear a muumuu.",
    "Release the hounds!",
    "Worst episode ever.",
    "Don't have a cow, man!",
    "Excellent!",
    "Won't somebody please think of the children?",
    "Thank you, come again!",
    "I, for one, welcome our new insect overlords.",
    "I am so smart! S-M-R-T!",
    "Hi, everybody!",
    "Dental plan!",
    "Lisa needs braces!",
    "I bent my Wookiee.",
    "My cat's breath smells like cat food.",
    "You don't win friends with salad.",
    "Okily-dokily!",
    "Stupid sexy Flanders!",
    "Ay, caramba!",
    "I choo-choo-choose you.",
    "Mmm... donuts.",
    "I was saying Boo-urns.",
    "I have three kids and no money. Why can't I have no kids and three money?",
    "Woo-hoo!",
    "You'll have to speak up, I'm wearing a towel.",
    "I am the lizard queen!",
    "*Chuckles* I'm in danger.",
    "Mmm... forbidden donut.",
    "Nothing at all!",
    "Mmm... beer.",
    "It's still good! It's still good!",
    "Everything's coming up Milhouse!",
    "I didn't do it.",
    "Do it for her.",
    "A noble spirit embiggens the smallest man.",
    "In this house, we obey the laws of thermodynamics!",
    "It's a perfectly cromulent word.",
    "That's a problem for future Homer.",
    "Why, you little!",
    "I'm learnding!",
    "I'm helping!",
    "I used to be with it, but then they changed what 'it' was.",
    "Just because I don't care doesn't mean I don't understand.",
    "Mmm... floor pie.",
    "Mmm... sacrilicious.",
    "I call the big one Bitey.",
]
