"""Generate editor-completion stubs for the dynamic provider catalogs."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from roboz.llm.providers.catalog import model_attribute_name
from roboz.llm.providers.model_types import ChatModelSpec
from roboz.standard.providers.openrouter import EXAMPLE_OPENROUTER_MODELS

CATALOG_PYI_PATH = (
    Path(__file__).resolve().parents[1]
    / "src"
    / "roboz"
    / "standard"
    / "providers"
    / "openrouter"
    / "__init__.pyi"
)

_HEADER = '''\
"""Typing surface for :mod:`roboz.standard.providers.openrouter`.

AUTO-GENERATED by ``scripts/generate_provider_stubs.py``. Do not edit.
"""

from enum import StrEnum

from openai import OpenAI
from roboz.llm import LLMEndpoint
from roboz.tooling import LazyExternalDependency

from roboz.llm.providers.catalog import ProviderCatalog
from roboz.llm.providers.model_types import ChatModelSpec

OPENROUTER_BASE_URL: str
EXAMPLE_OPENROUTER_MODELS: tuple[ChatModelSpec, ...]

class OpenRouterApiKey(StrEnum):
    API_KEY: OpenRouterApiKey

def openrouter_client(api_key: str) -> OpenAI: ...
def openrouter_model_name(model: ChatModelSpec) -> str: ...
def openrouter_endpoint(model: ChatModelSpec, model_name: str) -> LLMEndpoint: ...

'''

_FOOTER = """\
example_openrouter: ExampleOpenRouterCatalog

__all__: list[str]
"""


def _class_block(
    class_name: str,
    models: tuple[ChatModelSpec, ...],
    endpoint_type: str,
) -> str:
    lines = [f"class {class_name}(ProviderCatalog):"]
    lines.append("    def __init__(self) -> None: ...")
    lines.extend(
        f"    {model_attribute_name(model.model_id)}: "
        f"LazyExternalDependency[{endpoint_type}]"
        for model in models
    )
    return "\n".join(lines) + "\n"


def render_catalog_pyi() -> str:
    return "".join(
        [
            _HEADER,
            _class_block(
                "ExampleOpenRouterCatalog", EXAMPLE_OPENROUTER_MODELS, "LLMEndpoint"
            ),
            "\n",
            _FOOTER,
        ]
    )


def _check(target: Path, expected: str) -> int:
    if not target.exists() or target.read_text(encoding="utf-8") != expected:
        print(
            f"{target} is stale; run scripts/generate_provider_stubs.py",
            file=sys.stderr,
        )
        return 1
    print(f"{target} is up to date")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail without writing when the committed stub is stale",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=CATALOG_PYI_PATH,
        help=argparse.SUPPRESS,
    )
    args = parser.parse_args(argv)
    rendered = render_catalog_pyi()
    if args.check:
        return _check(args.output, rendered)
    args.output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
